"""AENIN: Adaptive Edge-Node Interaction Network."""

from .core import (
    AENIN,
    AdaptiveEdgeNodeLayer,
    Config,
    ablation_study,
    adaptive_threshold,
    build_dataset,
    build_edge_index_and_attr,
    compute_cis,
    compute_group_pcs,
    compute_its,
    compute_pcs,
    compute_plv_matrix,
    diagnose_dataset,
    evaluate,
    extract_node_features,
    extract_roi_timeseries_fixed_aal,
    group_statistical_test,
    load_atlas,
    load_subjects,
    plot_cis_scores,
    plot_confusion_matrices,
    plot_cv_summary,
    plot_its_heatmap,
    plot_pcs_scores,
    plot_roc_curves,
    plot_statistical_tests,
    plot_training_curves,
    print_summary_table,
    process_subject,
    save_results_csv,
    set_seed,
    train_fold,
)

__all__ = [
    "AENIN",
    "AdaptiveEdgeNodeLayer",
    "Config",
    "set_seed",
    "load_atlas",
    "load_subjects",
    "build_dataset",
    "process_subject",
    "extract_roi_timeseries_fixed_aal",
    "compute_plv_matrix",
    "adaptive_threshold",
    "build_edge_index_and_attr",
    "extract_node_features",
    "train_fold",
    "evaluate",
    "diagnose_dataset",
    "compute_cis",
    "compute_its",
    "compute_pcs",
    "compute_group_pcs",
    "group_statistical_test",
    "plot_training_curves",
    "plot_confusion_matrices",
    "plot_roc_curves",
    "plot_cis_scores",
    "plot_its_heatmap",
    "plot_pcs_scores",
    "plot_statistical_tests",
    "plot_cv_summary",
    "save_results_csv",
    "print_summary_table",
    "ablation_study",
]

__version__ = "1.0.0"
